### ISSUE TITLE
After install started getting lisp nesting exceeds 'max-lisp-eval-depth

### ISSUE THREAD

**Issue by Timmymayes** [rswgnu/hyperbole#289]
Installed version 8.0.0 with from elpa. Right after which I noticed my helpful screens wouldn't quit with 'q' keypress becuase of "lisp nesting exceeds 'max-lisp-eval-depth". I uninstalled hyperbole and restarted emacs and issue is gone.

**Comment by rswgnu** [comment]
Thanks.  This is resolved in the pre-release of Hyperbole.  Could you try that by adding elpa-devel to your package manager like so:

(when (< emacs-major-version 27)
  (error "Hyperbole requires Emacs 27 or above; you are running version %d" emacs-major-version))
(require 'package)
(add-to-list 'package-archives '("gnu-devel" . "https://elpa.gnu.org/devel/"))
(unless (package-installed-p 'hyperbole)
  (package-refresh-contents)
  (package-install 'hyperbole))
(hyperbole-mode 1)

**Comment by rswgnu** [comment]
Use this git repo or the elpa-devel pre-release package for now.

**Comment by mekkamagnus** [comment]
I used the elpa-devel pre-release package 8.0.1 on Emacs 29. I'm still getting this error after many re-installs. Are there any updates to this? I'm really to exited to get into Hyperbole disabling quitting windows is really hard to get past.

**Comment by rswgnu** [comment]
This should have been fixed long ago.  Can you start up with ‘emacs -Q’ and them load Hyperbole from the install/setup instructions and see if you have this problem.  We need a way to regenerate the problem.If you use anything like spacemacs or doom emacs, we would need to know as well.-- rswOn Oct 21, 2023, at 5:20 PM, Mekael Turner ***@***.***> wrote:﻿
I used the elpa-devel pre-release package 8.0.1 on Emacs 29. I'm still getting this error after many re-installs. Are there any updates to this? I'm really to exited to get into Hyperbole disabling quitting windows is really hard to get past.
