### ISSUE TITLE
Utilize ripgrep if not tags file is found

### ISSUE THREAD

**Issue by 0xd61** [rswgnu/hyperbole#776]
First of all thanks for this awesome package!

I'm quite new to emacs and hyperbole. I was wondering is it possible to setup the smart-tags (for finding function definitions in source code files) to use ripgrep or silver searcher like [dumb-jump](https://github.com/jacktasia/dumb-jump) does? That way no additional tags files are necessary and it can easily support different languages. I haven't found a possibility when searching through [hmouse-tag.el](https://github.com/rswgnu/hyperbole/blob/master/hmouse-tag.el). But maybe I have missed something.
Currently I'm using dumb-jump and it works quite well, even with larger repositories (like the Linux kernel). I would be cool however, if hyperbole can be configured to use it in the background (or using ripgrep directly) when looking up function or variable definitions.

**Comment by matsl** [comment]
I tried to debug it down to the actual call to `rg` and noticed there was an error response about illegal regexp or something. The error message from rg(!?) had the suggestion to use the command line option `--pcre2.` I then checked my dumb-jump setup and noticed I had for some reason cleared the command line options. 🤯 

Adding `--pcre2` back again solved the issue for me. The source file I was testing was a c-file but dumb-jump handles it as c++.

```
(setq dumb-jump-rg-search-args "--pcre2")
```

🤷

**Comment by 0xd61** [comment]
hmm this config was set by default in my config. I have added it explicitly, but it did not change anything. Still the same error that the definition could not be found, when using hyperbole even though xref-find-definition finds it.

**Comment by matsl** [comment]
> I'm not experienced with elisp. But what I have found so far is that `xref-find-definitions` is not called.

That is correct. I had a deeper look at the code today and it is calling `xref-backend-definitions` directly. Maybe it is something with the tags handling as you point out. Maybe it can block further processing in some cases. I will take a look. Thanks for providing these details that helps on remote debugging.

**Comment by 0xd61** [comment]
> Can you send a small sample file with both the definition and a reference in the same file and we will check out what is happening.
> 
> You must be using the latest version of Hyperbole from either melpa or emacs-devel (updated today).

I've upgraded to the latest version (hyperbole-20250907.2255) but the issue still persists.

A simple example would be:

/tmp/test.c
```
typedef struct {
    int abc;
} Test_Struct;

int main(int argc, char **argv) {
    Test_Struct *test_struct = {0};
    return 0;
}
```

**Comment by 0xd61** [comment]
As suggested by you I configured the `tags-file-name` variable and set it to "TAGS". I can confirm now it is working properly. Thanks for your help!

**Comment by rswgnu** [comment]
This issue has been fixed in the master branch and will be deployed to
melpa shortly.  You should no longer have to configure any tags table
settings.  Give it a try.  I am closing the issue; thanks for pointing it
out and helping improve Hyperbole.

**Comment by 0xd61** [comment]
Thanks for the update. I works now and I can jump to the correct definition.
However, still get the error message, even though everything seems to be working:
`‘Test_Struct’ definition not found in identifier lookup/tag tables`

**Comment by rswgnu** [comment]
> typedef struct {
>     int abc;
> } Test_Struct;
> 
> int main(int argc, char **argv) {
>     Test_Struct test_struct = {0};
>     return 0;
> }

So here, in testing I find Hyperbole and dumb jump will now find the definition of Test_Struct if point is on 'test_struct' in line 6 but not if point is on 'Test_Struct' of the same line.  Is this what you see and what you are expecting?

**Comment by 0xd61** [comment]
dumb-jump only finds the definition if the cursor is on the type. So if I have my cursor on line 6 on the `Test_Struct` type and press {M-RET} it jumps to the definition name on line 3. If it is on the variable name, it stays on line 6. This is normal behavior for dumb-jump. Since dumb-jump is only searching via ripgrep or silver searcher it also does not always find the correct definition and sometimes proposes multiple targets in the minibuffer. But that is just how dumb-jump works. It is basically searching the project for the tag under the cursor and returns possible locations with some filtering.
So the jump to the location is working as expected. The only thing is that hyperbole still prints the error even though everything seems to be working.

**Comment by rswgnu** [comment]
Great.  If you find other features are not working properly or missing, feel free to bring it up.  I would encourage you to try out the Hyperbole subsystems after reading their manual sections, including HyRolo, HyWiki and the Koutliner and consider joining the very low-volume Hyperbole mailing list which you can subscribe to with {C-h h m j}.
